SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
SPASS -PGiven=0 -PProblem=0 galen6.dfg
