SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
SPASS -PGiven=0 -PProblem=0 galen5.dfg
