SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
SPASS -PGiven=0 -PProblem=0 galen7.dfg
