SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
SPASS -PGiven=0 -PProblem=0 galen4.dfg
