SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
SPASS -PGiven=0 -PProblem=0 galen1.dfg
