SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
SPASS -PGiven=0 -PProblem=0 galen10.dfg
