SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
SPASS -PGiven=0 -PProblem=0 galen9.dfg
