SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
SPASS -PGiven=0 -PProblem=0 galen3.dfg
