SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
SPASS -PGiven=0 -PProblem=0 galen2.dfg
