SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
SPASS -PGiven=0 -PProblem=0 galen8.dfg
