../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
../../../../sofronie/DL/cel/cel < input-go-5-all.test > output-go-5-all.txt
