../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
../../../../sofronie/DL/cel/cel < input-nci-9-all.test > output-nci-9-all.txt
