../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt
../../../../sofronie/DL/cel/cel < input-galen-7-one.test > output-galen-7-one.txt