../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt
../../../../sofronie/DL/cel/cel < input-galen-4-one.test > output-galen-4-one.txt