SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
SPASS -PGiven=0 -PProblem=0 go6.dfg
