SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
SPASS -PGiven=0 -PProblem=0 go7.dfg
