SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
SPASS -PGiven=0 -PProblem=0 go9.dfg
