SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
SPASS -PGiven=0 -PProblem=0 go4.dfg
