SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
SPASS -PGiven=0 -PProblem=0 go2.dfg
