SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
SPASS -PGiven=0 -PProblem=0 go1.dfg
