SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
SPASS -PGiven=0 -PProblem=0 go5.dfg
