SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
SPASS -PGiven=0 -PProblem=0 go8.dfg
