SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
SPASS -PGiven=0 -PProblem=0 go3.dfg
