../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt
../../../../sofronie/DL/cel/cel < input-nci-7-one.test > output-nci-7-one.txt