../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt
../../../../sofronie/DL/cel/cel < input-nci-6-one.test > output-nci-6-one.txt