../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
../../../../sofronie/DL/cel/cel < input-go-10-all.test > output-go-10-all.txt
