../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
../../../../sofronie/DL/cel/cel < input-go-9-all.test > output-go-9-all.txt
