../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
../../../../sofronie/DL/cel/cel < input-go-3-all.test > output-go-3-all.txt
