../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
../../../../sofronie/DL/cel/cel < input-nci-2-all.test > output-nci-2-all.txt
