../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt
../../../../sofronie/DL/cel/cel < input-galen-1-all.test > output-galen-1-all.txt