../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt
../../../../sofronie/DL/cel/cel < input-galen-6-all.test > output-galen-6-all.txt