../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt
../../../../sofronie/DL/cel/cel < input-nci-1-one.test > output-nci-1-one.txt