SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
SPASS -PGiven=0 -PProblem=0 nci7.dfg
