SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
SPASS -PGiven=0 -PProblem=0 nci4.dfg
