SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
SPASS -PGiven=0 -PProblem=0 nci1.dfg
