SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
SPASS -PGiven=0 -PProblem=0 nci2.dfg
