SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
SPASS -PGiven=0 -PProblem=0 nci9.dfg
