SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
SPASS -PGiven=0 -PProblem=0 nci8.dfg
