SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
SPASS -PGiven=0 -PProblem=0 nci6.dfg
