SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
SPASS -PGiven=0 -PProblem=0 nci5.dfg
