SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
SPASS -PGiven=0 -PProblem=0 nci3.dfg
