../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
../../../sofronie/DL/cel/cel < input-nci-prep.test > output-nci-prep.txt
