../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
../../../../sofronie/DL/cel/cel < input-galen-10-one.test > output-galen-10-one.txt
