../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt
../../../../sofronie/DL/cel/cel < input-galen-3-all.test > output-galen-3-all.txt