../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt
../../../../sofronie/DL/cel/cel < input-go-1-all.test > output-go-1-all.txt